# Generated by Django 2.2.7 on 2020-03-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200324_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='imp',
            field=models.CharField(default='ok', max_length=120),
        ),
    ]
