# Generated by Django 2.2.7 on 2020-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='after_imp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
