# Generated by Django 2.2.7 on 2020-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_after_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='Technology', max_length=40),
        ),
    ]
