# Generated by Django 2.2.7 on 2020-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='html_disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='html_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag2',
            field=models.CharField(default='Technology', max_length=40),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag3',
            field=models.CharField(default='Technology', max_length=40),
        ),
    ]
