# Generated by Django 2.2.7 on 2020-03-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/port')),
                ('title', models.CharField(max_length=120)),
                ('tag', models.CharField(default='WebDevelopment', max_length=40)),
                ('date', models.DateField()),
                ('html_keywords', models.TextField(blank=True, null=True)),
                ('html_disc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
